### PR TITLE
HealthCache: improvements for external use

### PR DESCRIPTION
**Pull request by ckamm**
This makes it easier to use the HealthCache externally, which I use for the liquidatable-accounts-feed.

### CODE REVIEW

**Comment by ckamm** [comment]
This changes the semantics slightly: all open orders accounts that are passed will be attempted to be loaded, even if their market is not in_margin_basket.

**Comment by dafyddd** [comment]
Ok I'm going to push out v3.3.0 to mainnet, and I think this requires a bit more review. So maybe you can give this PR to main as per the new branch rules and I can merge it in their without deploying to mainnet

**Comment by dafyddd** [comment]
Do you think there's something lost in readability from the T: Deref<..> instead of &OpenOrders or Ref<OpenOrders>? Do you have an example of where you're using this function from elsewhere?

**Comment by ckamm** [comment]
Ok, will target `main` instead.

Yes, there's more cognitive overhead with being generic over `T: Deref<...>`. I want it to work with plain `&OpenOrders` because that's what I end up with in https://github.com/blockworks-foundation/liquidatable-accounts-feed/blob/master/src/main.rs#L148.

In mango-v3 we likely always have `Ref<OpenOrders->` because that's what we get from `AccountInfo`.

If it seems too confusing, I'd also be open to making it separate functions.

**Comment by dafyddd** [comment]
Nah, not that confusing. If there's a legitimate use case no problem

**Comment by dafyddd** [comment]
Can you reopen PR but so it's pointing at main and conflicts are resolved?

**Pull request merged**
