### PR TITLE
Interest Rate Calculation Helper Function

### PR DESCRIPTION
**Pull request by bonedaddy**
Pulls out the interest rate calculation logic from `RootBank::update_index` and makes it a helper function.

### CODE REVIEW

**Comment by ckamm** [comment]
@bonedaddy Looks good to me, thanks! Could you make the new helper functions `#[inline(always)]` to avoid any potential stack issues?

**Comment by bonedaddy** [comment]
@ckamm added

**Review by ckamm — APPROVED** [review]

**Comment by ckamm** [comment]
On CI:
- the cargo audit failures have already been dealt with on `main`
- Lint and test fails because of formatting, Run `cargo fmt`. I can't push to your branch, so you'll need to do it.
- the UXD composition test fails during setup, because it can't read the secret access token, not sure why that is - I'd not consider it a blocker

**Comment by ckamm** [comment]
I've moved this to #157, squashed and applied cargo fmt. There we'll check if CI passes and then merge.

**Pull request closed without merging**
