### PR TITLE
update anchor version and cargo deps and switchboard version

### PR DESCRIPTION
**Pull request by dafyddd**

### CODE REVIEW

**Comment by dafyddd** [comment]
@acamill Is it necessary that we stay with solana program 1.9.1? can you update to 1.9.4?

**Comment by acamill** [comment]
> @acamill Is it necessary that we stay with solana program 1.9.1? can you update to 1.9.4?

No we this is a mistake we don't require a specific version, was to follow the one you guys used

**Comment by acamill** [comment]
I'll push a change for the CI to pass, no need to do any change to the onchain program if I understand correctly how dependencies work.

**Comment by ckamm** [comment]
it looks like this is downgrading solana from 1.9.7 to 1.9.4, I wonder why that is

**Comment by ckamm** [comment]
It's because `switchboard-utils` now pins the solana version:
```
[dependencies.solana-program]
version = "=1.9.4"
```
We'll need to ask them about that.

**Review by ckamm — APPROVED** [review]

**Pull request merged**
